### ISSUE TITLE
Module 2 Subitizing 4. Your Turn Observing ... intro 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#196]
In first paragraph change course to learning experience

To more clear under In this exercise ... change first bullet to
Observe targeted steps and foundational math strategies ...
Third bullet change children's to students'

**Comment by castl350** [comment]
Changed students. I took off course but did not add learning experience. This is a clunky term and it's fine to simply keep it at "foundational strategies we introduced"..I think we're actually fine calling this a course...or a series of learning modules as far as i know. I'm leaving the observe bullet as is for now since it's still a targeted strategy as a whole...gets too confusing and wordy otherwise.
