### ISSUE TITLE
Module 2 Subitizing TYK - test

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#200]
#1 add periods to each of the items? I see that we do that for some ... 
c - add a comma after less than 

#2 take out says (there are 2 of them) and capitalize the word yes 

"Four!", he says, "Yes, look! ...

#3 capitalize the word how - ... and then asks students, "How many ... 
- add quotation marks after all together
- add a comma after say and capitalize yes - students say, "Six!", she says, "Yes, look!
- We need to be consistent with the altogether/all together especially when we use them in the same sentence ... not sure which one it is but I think that we need to be consistent

#4 would it be more clear/consistent to say following three targeted steps vs components

#5 is a repeat of one of the CYK questions - I think that it's okay but just wanted to note in case we think that it's not?

#6 
- change struggle to struggles 
- would it be more clear/consistent to say, "... the following targeted steps could be beneficial EXCEPT:"

#7 change for to 'to' - ... you could show smaller numbers of objects to students ... larger numbers of objects to student who need more ...

**Comment by castl350** [comment]
#1 - the periods and not periods are consistent here. The phrases that are not sentences don't have periods. And potential choices that are complete answers have periods.

#2 has been updated

#3 has been updated

#4 i agree although components is what we used in the lesson, but i think i shifted to steps because at times components was confusing....

#5 is ok...

#6 I agree..and i changed it to this....Mr. DuBose has observed his student, Charles, struggles during subitizing activities. In order for Mr. DuBose to provide support to Charles, she could adapt the activity to benefit Charles in all of the following ways EXCEPT:

#7 i'll change it although i think both work since it's not referencing the act of showing the card "to"s someone..it's adapting the lesson for a student...
