### ISSUE TITLE
STEP Intro Breadcrumb name

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#77]
Just checking to make sure it's ok to keep the course name abbreviated as "STEP Intro" here instead of "STEP Module 1: Introduction to Early Math" ?

Also, Numeracy appears as "NUMERACY SKILL 1: SUBITIZING" instead of STEP Module 2: Numeracy. For this, I think we should stay away from using numbers because learners may not take these modules in the same sequence.

**Comment by castl350** [comment]
I think this is ok..the breadcrumbs need to be clear but not long...Also on numeracy, 1 and 2 only appear when you are working on lessons at the session level..it's ok for numbers to be there because even if those skills are completed out of order, they're part of the same area....as long as we don't call the areas by number? hope that helps.
