### ISSUE TITLE
Overall Grades

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#79]
The "Grades" area on the sidebar is available to students & displays scores their %. Just wanted to make sure we want to display grades?

**Comment by castl350** [comment]
Matt, i feel like this came up in toddler too? are you talking about the left hand side bars...that there is a link Sarah?

**Comment by mattsema** [comment]
That link becomes available when any course is set to be graded.  We need to have the course graded in order for activity tracking to work.  Unfortunately, the link can not be removed because of the way those sidebars are created.

I haven't heard any problems from teachers about this.  They should know that they are not being officially graded.
